api:
    uri: https://cdn-api.co-vin.in/api
    endpoints:
        findByPin: /v2/appointment/sessions/public/findByPin
        findByDistrict: /v2/appointment/sessions/public/findByDistrict
        calendarByPin: /v2/appointment/sessions/public/calendarByPin
        calendarByDistrict: /v2/appointment/sessions/public/calendarByDistrict

bot:
    timeout: 10 #(put value in seconds)

user:
    pincodes: 414001 414005 